const icons = [
    "fa-solid fa-user", "fa-regular fa-user", "fa-solid fa-users", "fa-solid fa-user-plus", "fa-solid fa-user-shield", "fa-solid fa-user-secret",
    "fa-solid fa-house", "fa-solid fa-house-user", "fa-solid fa-magnifying-glass", "fa-solid fa-bars", "fa-solid fa-ellipsis", "fa-solid fa-envelope", "fa-regular fa-envelope", "fa-solid fa-inbox",
    "fa-solid fa-heart", "fa-regular fa-heart", "fa-solid fa-heart-crack", "fa-solid fa-star", "fa-regular fa-star", "fa-solid fa-star-half-stroke",
    "fa-solid fa-check", "fa-solid fa-check-double", "fa-solid fa-xmark", "fa-solid fa-music", "fa-solid fa-headphones", "fa-solid fa-volume-high",
    "fa-solid fa-image", "fa-regular fa-image", "fa-solid fa-camera", "fa-solid fa-video", "fa-solid fa-film", "fa-solid fa-clapperboard",
    "fa-solid fa-circle-check", "fa-regular fa-circle-check", "fa-solid fa-circle-xmark", "fa-regular fa-circle-xmark", "fa-solid fa-circle-info", "fa-solid fa-circle-exclamation",
    "fa-solid fa-download", "fa-solid fa-upload", "fa-solid fa-cloud-arrow-down", "fa-solid fa-cloud-arrow-up",
    "fa-solid fa-share", "fa-solid fa-share-nodes", "fa-solid fa-reply", "fa-solid fa-thumbs-up", "fa-regular fa-thumbs-up", "fa-solid fa-thumbs-down", "fa-regular fa-thumbs-down",
    "fa-solid fa-comment", "fa-regular fa-comment", "fa-solid fa-comments", "fa-regular fa-comments", "fa-solid fa-message",
    "fa-solid fa-quote-left", "fa-solid fa-quote-right", "fa-solid fa-pen", "fa-solid fa-pencil", "fa-solid fa-pen-nib", "fa-solid fa-eraser",
    "fa-solid fa-trash", "fa-regular fa-trash-can", "fa-solid fa-gear", "fa-solid fa-gears", "fa-solid fa-wrench", "fa-solid fa-screwdriver-wrench",
    "fa-solid fa-list", "fa-solid fa-list-check", "fa-solid fa-folder", "fa-regular fa-folder", "fa-solid fa-folder-open", "fa-regular fa-folder-open",
    "fa-solid fa-file", "fa-regular fa-file", "fa-solid fa-file-pdf", "fa-solid fa-file-word", "fa-solid fa-file-excel", "fa-solid fa-file-code", "fa-solid fa-file-image", "fa-solid fa-file-audio", "fa-solid fa-file-video",
    "fa-solid fa-code", "fa-solid fa-terminal", "fa-solid fa-bug", "fa-solid fa-laptop-code", "fa-solid fa-microchip", "fa-solid fa-memory",
    "fa-solid fa-hard-drive", "fa-solid fa-server", "fa-solid fa-database", "fa-solid fa-network-wired", "fa-solid fa-cloud",
    "fa-solid fa-wifi", "fa-solid fa-signal", "fa-solid fa-battery-full", "fa-solid fa-plug", "fa-solid fa-power-off",
    "fa-solid fa-desktop", "fa-solid fa-laptop", "fa-solid fa-mobile-screen", "fa-solid fa-tablet-screen-button", "fa-solid fa-keyboard", "fa-solid fa-mouse",
    "fa-solid fa-print", "fa-solid fa-floppy-disk", "fa-regular fa-floppy-disk", "fa-solid fa-bell", "fa-regular fa-bell",
    "fa-solid fa-calendar", "fa-regular fa-calendar", "fa-solid fa-calendar-days", "fa-solid fa-clock", "fa-regular fa-clock", "fa-solid fa-hourglass",
    "fa-solid fa-location-dot", "fa-solid fa-map", "fa-solid fa-compass", "fa-regular fa-compass", "fa-solid fa-signs-post",
    "fa-solid fa-car", "fa-solid fa-truck", "fa-solid fa-bicycle", "fa-solid fa-motorcycle", "fa-solid fa-plane", "fa-solid fa-train", "fa-solid fa-rocket", "fa-solid fa-ship", "fa-solid fa-anchor",
    "fa-solid fa-money-bill", "fa-regular fa-money-bill-1", "fa-solid fa-credit-card", "fa-regular fa-credit-card", "fa-solid fa-wallet", "fa-solid fa-piggy-bank",
    "fa-solid fa-cart-shopping", "fa-solid fa-basket-shopping", "fa-solid fa-bag-shopping", "fa-solid fa-tag", "fa-solid fa-tags", "fa-solid fa-percent", "fa-solid fa-gift",
    "fa-solid fa-trophy", "fa-solid fa-medal", "fa-solid fa-award", "fa-solid fa-crown", "fa-solid fa-gamepad", "fa-solid fa-puzzle-piece", "fa-solid fa-dice",
    "fa-solid fa-ghost", "fa-solid fa-skull", "fa-solid fa-book", "fa-solid fa-book-open", "fa-solid fa-graduation-cap", "fa-solid fa-school",
    "fa-solid fa-lightbulb", "fa-regular fa-lightbulb", "fa-solid fa-sun", "fa-regular fa-sun", "fa-solid fa-moon", "fa-regular fa-moon",
    "fa-solid fa-cloud-rain", "fa-solid fa-bolt", "fa-solid fa-snowflake", "fa-solid fa-fire", "fa-solid fa-water", "fa-solid fa-droplet", "fa-solid fa-wind",
    "fa-solid fa-leaf", "fa-solid fa-tree", "fa-solid fa-seedling", "fa-solid fa-paw", "fa-solid fa-dog", "fa-solid fa-cat", "fa-solid fa-fish", "fa-solid fa-dragon",
    "fa-solid fa-globe", "fa-solid fa-earth-americas", "fa-solid fa-earth-europe", "fa-solid fa-lock", "fa-solid fa-unlock", "fa-solid fa-key", "fa-solid fa-shield-halved",
    "fa-solid fa-eye", "fa-regular fa-eye", "fa-solid fa-eye-slash", "fa-regular fa-eye-slash", "fa-solid fa-fingerprint",
    "fa-solid fa-link", "fa-solid fa-paperclip", "fa-solid fa-scissors", "fa-solid fa-filter", "fa-solid fa-sort",
    "fa-solid fa-arrow-up", "fa-solid fa-arrow-down", "fa-solid fa-arrow-left", "fa-solid fa-arrow-right", "fa-solid fa-rotate-right", "fa-solid fa-rotate-left",
    "fa-solid fa-play", "fa-solid fa-pause", "fa-solid fa-stop", "fa-solid fa-forward", "fa-solid fa-backward",
    "fa-brands fa-facebook", "fa-brands fa-twitter", "fa-brands fa-instagram", "fa-brands fa-linkedin", "fa-brands fa-github", "fa-brands fa-discord", "fa-brands fa-youtube", "fa-brands fa-twitch", "fa-brands fa-tiktok",
    "fa-brands fa-whatsapp", "fa-brands fa-telegram", "fa-brands fa-signal", "fa-brands fa-pinterest", "fa-brands fa-reddit", "fa-brands fa-snapchat", "fa-brands fa-spotify", "fa-brands fa-soundcloud",
    "fa-brands fa-apple", "fa-brands fa-windows", "fa-brands fa-linux", "fa-brands fa-android", "fa-brands fa-docker", "fa-brands fa-php", "fa-brands fa-js", "fa-brands fa-html5", "fa-brands fa-css3", "fa-brands fa-python", "fa-brands fa-java", "fa-brands fa-rust", "fa-brands fa-react", "fa-brands fa-vuejs", "fa-brands fa-angular", "fa-brands fa-node", "fa-brands fa-npm", "fa-brands fa-git", "fa-brands fa-gitlab", "fa-brands fa-bitbucket",
    "fa-brands fa-aws", "fa-brands fa-google", "fa-brands fa-microsoft", "fa-brands fa-paypal", "fa-brands fa-stripe", "fa-brands fa-bitcoin", "fa-brands fa-ethereum", "fa-brands fa-chrome", "fa-brands fa-firefox", "fa-brands fa-edge", "fa-brands fa-safari"
];